### ISSUE TITLE
Docker image runs of memory during build

### ISSUE THREAD

**Issue by gibsonjoshua55** [boyney123/eventcatalog#325]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

I generated an event catalog using `npx @eventcatalog/create-eventcatalog@latest [name]` and running `docker build` leads to a build error.

The build does not finish and exits with error code 137.  This looks to be a memory issue but running the image with increased memory (`--memory=4g`) and setting the node memory limit `export NODE_OPTIONS="--max-old-space-size=4096"` did not resolve the issue.

I have not modified the code at all from the generated repository

### Steps to reproduce

```
npx @eventcatalog/create-eventcatalog@latest test-catalog
cd test-catalog
yarn install
docker build .
```

### Expected behavior

It would build complete the build step and not error.

### Actual behavior

It fails during the build stage

```
info  - Creating an optimized production build ...Killed
...
Error: Command failed: cross-env PROJECT_DIR=/app npm run build
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Command.<anonymous> (/app/node_modules/@eventcatalog/core/bin/eventcatalog.js:60:5)
    at Command.listener (/app/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/app/node_modules/commander/index.js:651:12)
    at Command.parse (/app/node_modules/commander/index.js:474:21)
    at run (/app/node_modules/@eventcatalog/core/bin/eventcatalog.js:115:7)
    at Object.<anonymous> (/app/node_modules/@eventcatalog/core/bin/eventcatalog.js:122:1) {
  status: 137,
  signal: null,
  output: [ null, null, null ],
  pid: 64,
  stdout: null,
  stderr: null
}
```

### Your environment

- EventCatalog version used: 0.6.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac 12.2.1/Docker Desktop 4.9.0

**Comment by boyney123** [comment]
docker file was updated, let me know if you still have this issue, going to close. Things working OK my side.

**Comment by 1bberto** [comment]
@boyney123 I had a similar issue on my local after getting the latest version of the `DockerFile`
I had to change `npm ci` to `npm install`, since on my computer I have `node18` and the `package-lock.json` was generated from that node version. 
When trying to create the image I was getting the same error `Command failed: cross-env PROJECT_DIR='/app' npm run build`, though after changing to `npm install` I was able to get rid of the issue

**Comment by Laupetin** [comment]
Sorry for bumping this old issue, I'm currently experiencing the same issue however.
I am trying to build the Dockerfile in our CI which uses Pods that have their memory capped at 4GB.
I tried making use of the `--max-old-space-size` option as well without any noticable impact.
80% of the time the CI run dies due to being out of memory with a small chance of it running through regardless.

![Screenshot_20240429_174854](https://github.com/boyney123/eventcatalog/assets/9197140/7c55536f-5112-4a3a-aa53-78cdca8d4e8c)

By temporarly trying to increase the limit to 6GB, the runs were a lot more likely to succeed, the build didn't have any problems to fully make use of the entire memory in that case as well though.

In any case, taking this much memory is a bit odd. I didn't encounter any issues with other builds being limited to 4GB yet.
