### ISSUE TITLE
3d node graph is broken

### ISSUE THREAD

**Issue by nahidakbar** [boyney123/eventcatalog#329]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

![Uploading image.png…]()

### Steps to reproduce

Browse to https://app.eventcatalog.dev/overview/

### Expected behavior

Expect to see something that is not an error message.

### Actual behavior

We see an error message.

### Your environment

- EventCatalog version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

Three.js demos work fine on my browser. Error message (missing definition) indicates it is most likely a missing import issue.

**Comment by michelgrootjans-conundra** [comment]
The link to CSS2Renderer.js via CDN is broken because of a new version of three.js that changed the example directory structure from _examples/js/renderers_ to examples/**jsm**/renderers.

 This is the current chain:
- html.heads links to https://unpkg.com/three/examples/js/renderers/CSS2DRenderer.js
- unpkg redirects to https://unpkg.com/three@0.148.0/examples/js/renderers/CSS2DRenderer.js
- this url fails with error _Cannot find "/examples/js/renderers/CSS2DRenderer.js" in three@0.148.0_

Possible solutions.
- link to a hardcoded version of three.js: https://unpkg.com/three@0.145.0/examples/js/renderers/CSS2DRenderer.js
  - this fixes the 3d view
- change the link to follow the latest version's directory structure: https://unpkg.com/three/examples/jsm/renderers/CSS2DRenderer.js

Extra remarks
- html.head already points to a hardcoded version of three.js: https://unpkg.com/three@0.145.0/build/three.min.js

My current workaround:
- an extra `postbuild` script that changes the generated files: `find .eventcatalog-core .next out -name "*.html" | xargs -L1 sed -i '' 's/unpkg.com\/three\//unpkg.com\/three@0.145.0\//g'`

**Comment by boyney123** [comment]
Thank you for raising @nahidakbar , and thank you for fixing @michelgrootjans-conundra , will get this fix out now
