### ISSUE TITLE
Ability to generate AsyncAPI file from Docs (Services and Events)

### ISSUE THREAD

**Issue by boyney123** [boyney123/eventcatalog#80]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

EventCatalog allows you to define your event and services using markdown.

With the new plugin system (Coming) you can generate these docs using various tools (think spec first > docs, or code > docs).

What about **docs > spec?**

For example, if people have events and services documented and maybe schemas, then there should be no real reason why we can't generate AsyncAPI specs from this?

Maybe add a button on the UI that generates the spec file?

### Motivation

Give people another option to get value from their docs into spec files.

With AsyncAPI you can do all sorts, like generate models, applications etc.

**Comment by thim81** [comment]
AsyncAPi is a structured document, perfect for documentation and visualisation but it can also be used to generate clients.

While EventCatalog feels more like a "hub" to point towards the events & services documentation, generating an asyncAPI spec from the EventCatalog defined events would be interesting to kick-start the AsyncAPI writing.
But it would require plenty more manual additions and/or EventCatalog properties to make it a complete AsyncAPI like: channels, servers + you would end-up with a less-dry specification, since it would be difficult to generate a spec which uses $references.

The other way around would be my preferred workflow, define the AsyncAPI specification with re-usable schemas and generate "events" and JSON schemas out it.

But both can perfectly co-exists within EventCatalog, it is a matter of workflow.

**Comment by boyney123** [comment]
Yeah interesting, guess as you said there would be loads to consider (channels, etc), and it could complicate things pretty fast.

`The other way around would be my preferred workflow, define the AsyncAPI specification with re-usable schemas and generate "events" and JSON schemas out it.`, yeah great let's start here for now with the plugin system and see how things go from there.

**Comment by boyney123** [comment]
AsyncAPI is now support as a plugin for eventcatalog, going to close this one for now 👍
